### ISSUE TITLE
最新的脚本转跳的时候不能把文本带过去，%s变成了搜索

### ISSUE THREAD

**Issue by arpir** [all-search/all-search#57]
脚本转跳的时候不能把输入框里的文本带过去，%s变成了搜索。

**Comment by endday** [comment]
提供下具体的网站，不是所有的网站都可以正常获取关键字的

**Comment by NOthing2O2O** [comment]
> 提供下具体的网站，不是所有的网站都可以正常获取关键字的

我使用bing（www.bing.com）搜索跳转无法获取关键字，未使用必应（www.cn.bing.com）测试。

**Comment by endday** [comment]
> > 提供下具体的网站，不是所有的网站都可以正常获取关键字的
> 
> 我使用bing（www.bing.com）搜索跳转无法获取关键字，未使用必应（www.cn.bing.com）测试。

我又测试了一下www.bing.com，是正常的
麻烦你测试下你浏览器访问www.bing.com的情况

**Comment by arpir** [comment]
抱歉啊，现在已经没有使用这个脚本了，已经转换到searchEngineJumple 了，如果没有其他人反馈同类的问题，可能是其他脚本冲突也不一定。

endday ***@***.***> 于2023年12月24日周日 11:35写道：
