### ISSUE TITLE
[建议] 全局弹窗搜索可选择关闭

### ISSUE THREAD

**Issue by o-liverkk** [all-search/all-search#60]
你好，

希望全局弹窗搜索的悬浮窗（竖排的三个点）能关掉。

或者告知用户应该删除哪些代码，这个悬浮窗经常点错。

谢谢。

**Comment by endday** [comment]
项目走了打包，你想直接删恐怕有点困难，我加一个开关吧

**Comment by o-liverkk** [comment]
感谢开发
