### ISSUE TITLE
能不能增加一个关于划词的选项

### ISSUE THREAD

**Issue by wolfan** [all-search/all-search#71]
其实并不需要这个功能，因为有其它插件在执行相关的操作，比如超级拖拽。而且划词的同时也还有其它功能，如 沙拉翻译，荧光笔 等插件。所以划词搜索这功能真的很占地方而且鸡肋。

希望可以在配置页面增加一个关闭选项，万切。

**Comment by endday** [comment]
> 其实并不需要这个功能，因为有其它插件在执行相关的操作，比如超级拖拽。而且划词的同时也还有其它功能，如 沙拉翻译，荧光笔 等插件。所以划词搜索这功能真的很占地方而且鸡肋。
> 
> 希望可以在配置页面增加一个关闭选项，万切。

侧边栏配置可以直接关闭的
