### ISSUE TITLE
百度搜索显示覆盖的bug

### ISSUE THREAD

**Issue by PandaFang** [all-search/all-search#73]
百度搜索结果页面选中文字会百度自带快速搜索按钮，本来它是出现在选中那几个字的上方一行的，但是开启了本脚本，横向显示的话，它会出现覆盖住选中文字的位置，造成无法用鼠标右键来复制文字，只能通过ctrl+c 复制。

**Comment by endday** [comment]
最新的版本已经修复这个问题了，感谢反馈
