### ISSUE TITLE
自定义的工具栏是否可以添加图标这一功能

### ISSUE THREAD

**Issue by QiQi777iii** [all-search/all-search#76]
![image](https://github.com/all-search/all-search/assets/141505720/4532aa34-0c11-4a78-8893-f9d104227b9d)
自带的都有图标显示，但是自定义的没有找到在哪里有添加图标的选项希望可以解答下谢谢

**Comment by endday** [comment]
分类的图标其实是我自己写死在代码里的，我考虑下要不要支持自定义图标哈

**Comment by QiQi777iii** [comment]
好的麻烦你了
