### ISSUE TITLE
百度搜索后点相关搜索后all-search会显示错误，图标变很大，刷新后能恢复

### ISSUE THREAD

**Issue by leungxt** [all-search/all-search#77]
<img width="1282" alt="屏幕截图 2024-02-11 001513" src="https://github.com/all-search/all-search/assets/51778432/f34269e6-6a7f-44a7-94d3-af8bbd7a66a9">

1.5.3和1.5.2出现问题，百度搜索后点相关搜索后all-search会显示错误，图标变很大，刷新后能恢复。

**Comment by endday** [comment]
感谢反馈

**Comment by endday** [comment]
1.5.4版本已修复，感谢反馈
