### ISSUE TITLE
1.5.4工具栏自定义后无效

### ISSUE THREAD

**Issue by leungxt** [all-search/all-search#79]
再报一个1.5.4的bug，工具栏自定义后无效，还是显示默认的百度和百度翻译，点击“三个点”后界面也是空白的。
<img width="650" alt="1" src="https://github.com/all-search/all-search/assets/51778432/4007fbd8-be38-4555-a3b0-aafad20da251">
<img width="936" alt="2" src="https://github.com/all-search/all-search/assets/51778432/ef006b97-6cc9-481c-b5c1-f084de49660f">
<img width="1148" alt="3" src="https://github.com/all-search/all-search/assets/51778432/0db54ff1-8ade-4902-b42a-1747a35107f6">

**Comment by endday** [comment]
感谢反馈，问题已修复
