### ISSUE TITLE
MAC 的火狐浏览器使用划词搜索功能,恳请修复一下,谢谢!

### ISSUE THREAD

**Issue by binart1943** [all-search/all-search#80]
苹果电脑 MAC 的火狐浏览器,除了在百度搜索页面之外,都无法使用划词搜索功能,之前1.410版是可以的,现在失灵了很可惜!
恳请修复一下,谢谢!

**Comment by endday** [comment]
> 苹果电脑 MAC 的火狐浏览器,除了在百度搜索页面之外,都无法使用划词搜索功能,之前1.410版是可以的,现在失灵了很可惜! 恳请修复一下,谢谢!

我没有Mac的机器，如果可以，能不能帮忙截个图，按f12，打开开发者工具，然后看看有没有报错，截个图
![Uploading image.png…]()

类似这样的
